### ISSUE TITLE
Product category type is string. Must be objectId.

### ISSUE THREAD

**Issue by ankitkarna99** [shresthaoshan/burgeon-ecommerce-task#1]
Hi Oshan!

I think I will notify you with this github issue that the type of category field in Product Schema is set to string. Make it object id and remove the default value and set this to required.

**Comment by shresthaoshan** [comment]
Updated: [e4c865f142ee1dc684dc8b33bfffa5b8a29acce8](https://github.com/shresthaoshan/burgeon-ecommerce-task/commit/e4c865f142ee1dc684dc8b33bfffa5b8a29acce8)
