### ISSUE TITLE
Optimize product schema indexing.

### ISSUE THREAD

**Issue by ankitkarna99** [shresthaoshan/burgeon-ecommerce-task#2]
I see you have indexed the name. But, I would like you to make a compound full text index on "name" and "description" to make searching better. Please look into full text indexing and search using full text index in Mongoose. After you've done that use it to make a product search endpoint.

**Comment by shresthaoshan** [comment]
Awaiting review: [e0cd5d13fd9c41b3e253fb35ed6031b4543bf674](https://github.com/shresthaoshan/burgeon-ecommerce-task/commit/e0cd5d13fd9c41b3e253fb35ed6031b4543bf674)

**Comment by shresthaoshan** [comment]
@ankitkarna99 awaiting review: [e0cd5d13fd9c41b3e253fb35ed6031b4543bf674](https://github.com/shresthaoshan/burgeon-ecommerce-task/commit/e0cd5d13fd9c41b3e253fb35ed6031b4543bf674)

**Comment by ankitkarna99** [comment]
Well done ✅
