### ISSUE TITLE
Change field "user_id" to just "user" in cart schema.

### ISSUE THREAD

**Issue by ankitkarna99** [shresthaoshan/burgeon-ecommerce-task#3]
Please update the field name to make sure we do not get user_id if we populate the user.

**Comment by shresthaoshan** [comment]
Updated: [5b474859e3918d535f8d0286aa013da88af9e480](https://github.com/shresthaoshan/burgeon-ecommerce-task/commit/5b474859e3918d535f8d0286aa013da88af9e480)
