### ISSUE TITLE
Restful Implementation Issue in Product Endpoints

### ISSUE THREAD

**Issue by ankitkarna99** [shresthaoshan/burgeon-ecommerce-task#4]
Search and Get Products endpoints need to be get requests. Use req.params to get products and req.query for search query.

Since we are updating a product, a patch request makes more sense than post request. But not enforcing myself on this one. This change is optional.

**Comment by shresthaoshan** [comment]
Updated: [e4c865f142ee1dc684dc8b33bfffa5b8a29acce8](https://github.com/shresthaoshan/burgeon-ecommerce-task/commit/e4c865f142ee1dc684dc8b33bfffa5b8a29acce8)
