### ISSUE TITLE
Restful Implementation issues for cart endpoints.

### ISSUE THREAD

**Issue by ankitkarna99** [shresthaoshan/burgeon-ecommerce-task#5]
Delete from cart needs to be a delete request rather than post, use req.params to send id that needs to be deleted.

Get cart items need to be a get request.

**Comment by shresthaoshan** [comment]
* Remove cart endpoint changed to DELETE: [d922045d239a4e84686032da552bbe87ccb40bed](https://github.com/shresthaoshan/burgeon-ecommerce-task/commit/d922045d239a4e84686032da552bbe87ccb40bed)
* Get cart endpoint changed to GET: [5a1fe4075c8e3472231d1407a6a3ad29ccc54c44](https://github.com/shresthaoshan/burgeon-ecommerce-task/commit/5a1fe4075c8e3472231d1407a6a3ad29ccc54c44)
