### ISSUE TITLE
Need sort by meta textScore in Product Search!

### ISSUE THREAD

**Issue by ankitkarna99** [shresthaoshan/burgeon-ecommerce-task#7]
Sort will make better matched outputs appear first!

**Comment by shresthaoshan** [comment]
Review: [94f11646037ac8367b1721a87f6a9fbffcd8a7d0](https://github.com/shresthaoshan/burgeon-ecommerce-task/commit/94f11646037ac8367b1721a87f6a9fbffcd8a7d0)
